"""Placeholder table regeneration entry point.

Most experiment scripts write their own CSV and LaTeX-style table files under
`outputs/tables/`. This helper documents that convention and creates the
expected output directories.
"""

from __future__ import annotations

from pathlib import Path


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    for rel in ("outputs/results", "outputs/tables", "outputs/figures"):
        (root / rel).mkdir(parents=True, exist_ok=True)
    print("Table outputs are generated by the experiment scripts under outputs/tables/.")


if __name__ == "__main__":
    main()
